<?php
echo '<div id="container">
                <nav>
                    <div class="navigation">
                        <a href="index.html" title="Return to Homepage"><img src="images/logo.png" class="logo" alt="101 IT Company Logo"></a>
                        <ul class="navigation">
                            <li class="nav">
                                <a href="index.php" class="link">Home</a>
                            </li>
                            <li class="nav">
                                <a href="jobs.php" class="link">Job Openings</a>
                            </li>
                            <li class="nav">
                                <a href="apply.php" class="link">Submit Application</a>
                            </li>
                            <li class="nav">
                                <a href="services.php" class="link">Services</a>
                            </li>
                            <li class="nav">
                                <a href="enhancements.php" class="link">Enhancements</a>
                            </li>
                            <li class="nav">
                                <a href="about.php" class="link">About Us</a>
                            </li>
                         </ul>
                    </div>
                </nav>
            </div>';  
?>
